config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
                       omniauth_callbacks: "users/omniauth_callbacks",
                       registrations: "users/registrations",
                       passwords: "users/passwords",
                     }
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  root "posts#index"
  get "/users/:id", to: "users#show", as: "user"
  resources :users, only: %i(show destroy)
  resources :posts, expect: %i(show) do
    resources :photos, only: %i(create)
    resources :likes, only: %i(create destroy)
    resources :comments, only: %i(create destroy)
  end
  resources :introductions, only: %i(index)
  resources :movies, only: %i(index)
  resources :members, only: %i(index)
  resources :contacts, only: %i(index create)
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/contact.rb
class Contact < ApplicationRecord
  include Confirmable
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :contact_name, length: { maximum: 48 }
  validates :contact_email, presence: true, format: { with: VALID_EMAIL_REGEX }, length: { maximum: 256 }
  validates :content, presence: true, length: { maximum: 2000 }
  validates :remote_ip, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :url, presence: true
  before_save do
    format_url = YoutubeUrlFormatter.format(url)
    if format_url.present?
      self.url = format_url
    else
      self.errors.add(:url, "YouTubeのURL以外は無効です")
    end
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :post
  mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :photos
  paginates_per 20
  validates :text, length: { maximum: 1000 }

  def liked_by(current_user)
    Like.find_by(user_id: current_user.id, post_id: id)
  end
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :movies, dependent: :destroy
  has_many :sns_credentials, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]
  mount_uploader :profile_photo, ProfilePhotoUploader
  validates :name, presence: true, length: { maximum: 20 }
  validates :username, uniqueness: true
  validates :message, length: { maximum: 200 }

  def update_without_current_password(params, *options)
    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = sns.user || User.where(email: auth.info.email).first_or_initialize(
      name: auth.info.name,
      email: auth.info.email,
      username: auth.info.name,
    )
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end

  def self.guest
    find_or_create_by!(email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64(15)
      user.name = "ゲストユーザー"
      user.username = "ゲストユーザー"
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = current_user.likes.build(like_params)
    @post = @like.post
    if @like.save
      respond_to :js
    end
  end

  def destroy
    @like = Like.find_by(id: params[:id])
    @post = @like.post
    if @like.destroy
      respond_to :js
    end
  end

  private

  def like_params
    params.permit(:post_id)
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    @members = User.order(id: :DESC)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    def index
      @movies = Movie.order(id: :asc)
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i(show edit update destroy)
  PER_PAGE = 10

  def create
    post = Post.new(post_params)
    if post.text.present?
      post.save
      flash[:notice] = "投稿が保存されました"
    else
      flash[:alert] = "投稿に失敗しました"
    end
    redirect_to root_path
  end

  def index
    @post = Post.new
    @post.photos.build
    @posts = Post.includes(:photos, :user).order("created_at DESC").page(params[:page]).per(PER_PAGE)
  end

  def edit
  end

  def update
    if @post.update_attributes(post_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if @post.user == current_user
      flash[:notice] = "投稿が削除されました" if @post.destroy
    else
      flash[:alert] = "投稿の削除に失敗しました"
    end
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:text, photos_attributes: [:image]).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find_by(id: params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(id: params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy!
    flash[:notice] = "ユーザーを削除しました。"
    redirect_to :root
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def embed_youtube(url)
    tag.iframe(
      # width: 560,
      # height: 315,
      src: url,
      frameborder: 0,
      allow: "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture",
      allowfullscreen: true,
    )
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/likes/create.js.erb
$('#like-icon-post-<%= @post.id.to_s %>').
html('<%= link_to "いいねを取り消す", post_like_path(@post.id, @like), method: :DELETE, remote: true, class: "loved hide-text" %>');
$('#like-text-post-<%= @post.id.to_s %>').
html('<%= j render "posts/like_text", { likes: @post.likes } %>');

app/views/likes/destroy.js.erb
$('#like-icon-post-<%= @post.id.to_s %>').
html('<%= link_to "いいね", post_likes_path(@post), method: :POST, remote: true, class: "love hide-text" %>');
$('#like-text-post-<%= @post.id.to_s %>').
html('<%= j render "posts/like_text", { likes: @post.likes } %>');

app/views/posts/_comment_list.html.erb
<% post.comments.each do |comment| %>
  <div class="mb-2">
    <% if comment.user == current_user %>
      <%= link_to "", post_comment_path(post.id, comment), method: :delete, remote: true, class: "delete-comment" , data: { confirm: 'コメントを削除しますか？'}%>
    <% end %>
    <span>
      <strong>
        <%= link_to comment.user.username, user_path(comment.user), class: "no-text-decoration black-color" %>
      </strong>
    </span>
    <span><%= comment.comment %></span>
  </div>
<% end %>

app/views/posts/_like_text.html.erb
<strong>
  <% likes.each.with_index do |like, index| %>
    <% if likes.size == 1 %>
      <%= like.user.username %> </strong> さんが「いいね！」しました
  <% elsif like == likes.last %>
  </strong>and<strong>
    <%= + like.user.username %></strong> さんが「いいね！」しました
<% elsif index > 1 %>
</strong><%= "and " + (likes.size-index).to_s + " 他 " %> さんが「いいね！」しました
<% break %>
<% elsif index == likes.size-2 || index == 1 %>
  <%= like.user.username %>
<% else %>
  <%= like.user.username + ", " %>
<% end %>
<% end %>
</strong>

app/views/posts/edit.html.erb
<div class="d-flex flex-column align-items-center mt-3">
  <div class="col-xl-7 col-lg-8 col-md-10 col-sm-11 post-card">
    <div class="card">
      <div class="card-body">
        <%= form_with model: @post, class: "upload-images p-0 border-0" do |f| %>
          <div class="form-group row mt-2">
            <div class="col-auto pr-0">
              <%= image_tag @post.user.profile_photo.url, class: "post-profile-icon" %>
            </div>
            <div class="col pl-0">
              <%= f.text_field :text, class: "form-control border-1", required: true, maxlength: 1000 %>
            </div>
          </div>
          <%= f.submit "編集内容を投稿する", class: "btn btn-info btn-block"%>
          <%= link_to "やっぱり編集しない", root_path, class: "btn btn-secondary btn-block"%>
        <% end %>
      </div>
    </div>
  </div>

app/views/posts/index.html.erb
<div class="d-flex flex-column align-items-center mt-3">
  <div class="col-md-8 col-sm-11 post-card">
    <div class="card">
      <div class="card-body">
        <%= form_with model: @post, class: "upload-images p-0 border-0" do |f| %>
          <div class="form-group row mt-2">
            <div class="col-auto pr-0">
              <%= image_tag current_user.profile_photo.url, class: "post-profile-icon" %>
            </div>
            <div class="col pl-0">
              <%= f.text_field :text, class: "form-control text-input border-1", placeholder: "投稿を書く(最大1000字)", required: true, maxlength: 1000 %>
            </div>
          </div>
          <div class="d-flex flex-column mb-3">
            <%= f.fields_for :photos do |i| %>
              <%= i.file_field :image, accept: "image/png,image/jpeg,image/gif" %>
            <% end %>
          </div>
          <%= f.submit "投稿する", class: "btn btn-info btn-block" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% @posts.each do |post| %>
  <div class="col-md-8 col-md-2 mx-auto post-card">
    <div class="card-wrap">
      <div class="card">
        <div class="card-header align-items-center d-flex">
          <%= link_to user_path(post.user) do %>
            <%= image_tag post.user.profile_photo.url, class: "post-profile-icon" %>
          <% end %>
          <%= link_to user_path(post.user), class: "black-color",title: post.user.username do %>
            <strong><%= post.user.username %></strong>
          <% end %>
          <% if post.user_id == current_user.id %>
            <div class="list_actions mx-auto d-flex">
              <ul>
                <%= link_to content_tag(:i, '', class: 'fas fa-pen'), edit_post_path(post), class: "ml-auto mx-0 my-auto"%>
              </ul>
              <ul>
                <%= link_to content_tag(:i, '', class: 'fas fa-trash'), post_path(post), method: :delete, class: "ml-auto mx-0 my-auto", data: { confirm: '投稿を削除しますか？'} %>
              </ul>
            </div>
          <% end %>
        </div>
        <div class="text-box">
          <%= post.text%>
        </div>
        <% if post.photos.present? %>
          <%=image_tag post.photos.first.image.url, class: "card-img-top" %>
        <% end %>
        <div class="card-body">
          <div class="row parts">
            <div id="like-icon-post-<%= post.id.to_s %>">
              <% if post.liked_by(current_user).present? %>
                <%= link_to "いいねを取り消す", post_like_path(post.id, post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text" %>
              <% else %>
                <%= link_to "いいね", post_likes_path(post), method: :POST, remote: true, class: "love hide-text" %>
              <% end %>
            </div>
          </div>
          <div id="like-text-post-<%= post.id.to_s %>">
            <%= render "like_text", { likes: post.likes } %>
          </div>
          <div>
            <div id="comment-post-<%= post.id.to_s %>">
              <%= render 'comment_list', { post: post } %>
            </div>
            <div class="row actions" id="comment-form-post-<%= post.id.to_s %>">
              <%= form_with model: [post, Comment.new], class: "w-100" do |f| %>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <%= f.hidden_field :post_id, value: post.id %>
                <%= f.text_field :comment, class: "form-control comment-input border-1", placeholder: "コメント ...", autocomplete: :off, required: true, maxlength: 100 %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
<%= paginate @posts %>