config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
                       omniauth_callbacks: "users/omniauth_callbacks",
                       registrations: "users/registrations",
                       passwords: "users/passwords",
                     }
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  root "posts#index"
  get "/users/:id", to: "users#show", as: "user"
  resources :users, only: %i(show destroy)
  resources :posts, expect: %i(show) do
    resources :photos, only: %i(create)
    resources :likes, only: %i(create destroy)
    resources :comments, only: %i(create destroy)
  end
  resources :introductions, only: %i(index)
  resources :movies, only: %i(index)
  resources :members, only: %i(index)
  resources :contacts, only: %i(index create)
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/contact.rb
class Contact < ApplicationRecord
  include Confirmable
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :contact_name, length: { maximum: 48 }
  validates :contact_email, presence: true, format: { with: VALID_EMAIL_REGEX }, length: { maximum: 256 }
  validates :content, presence: true, length: { maximum: 2000 }
  validates :remote_ip, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :url, presence: true
  before_save do
    format_url = YoutubeUrlFormatter.format(url)
    if format_url.present?
      self.url = format_url
    else
      self.errors.add(:url, "YouTubeのURL以外は無効です")
    end
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :post
  mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :photos
  paginates_per 20
  validates :text, length: { maximum: 1000 }

  def liked_by(current_user)
    Like.find_by(user_id: current_user.id, post_id: id)
  end
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :movies, dependent: :destroy
  has_many :sns_credentials, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]
  mount_uploader :profile_photo, ProfilePhotoUploader
  validates :name, presence: true, length: { maximum: 20 }
  validates :username, uniqueness: true
  validates :message, length: { maximum: 200 }

  def update_without_current_password(params, *options)
    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = sns.user || User.where(email: auth.info.email).first_or_initialize(
      name: auth.info.name,
      email: auth.info.email,
      username: auth.info.name,
    )
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end

  def self.guest
    find_or_create_by!(email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64(15)
      user.name = "ゲストユーザー"
      user.username = "ゲストユーザー"
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = current_user.likes.build(like_params)
    @post = @like.post
    if @like.save
      respond_to :js
    end
  end

  def destroy
    @like = Like.find_by(id: params[:id])
    @post = @like.post
    if @like.destroy
      respond_to :js
    end
  end

  private

  def like_params
    params.permit(:post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i(show edit update destroy)
  PER_PAGE = 10

  def create
    post = Post.new(post_params)
    if post.text.present?
      post.save
      flash[:notice] = "投稿が保存されました"
    else
      flash[:alert] = "投稿に失敗しました"
    end
    redirect_to root_path
  end

  def index
    @post = Post.new
    @post.photos.build
    @posts = Post.includes(:photos, :user).order("created_at DESC").page(params[:page]).per(PER_PAGE)
  end

  def edit
  end

  def update
    if @post.update_attributes(post_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if @post.user == current_user
      flash[:notice] = "投稿が削除されました" if @post.destroy
    else
      flash[:alert] = "投稿の削除に失敗しました"
    end
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:text, photos_attributes: [:image]).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def embed_youtube(url)
    tag.iframe(
      # width: 560,
      # height: 315,
      src: url,
      frameborder: 0,
      allow: "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture",
      allowfullscreen: true,
    )
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DTM connect OKINAWA</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div id="wrapper">
      <%= render 'partial/navbar' if current_user %>
      <% if flash[:notice] %>
        <div class="alert alert-info">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert alert-danger">
          <%= flash[:alert] %>
        </div>
      <% end %>
      <div class="container">
        <%= yield %>
      </div>
      <%= render 'partial/footer' if current_user%>
    </div>
  </body>
</html>

app/views/partial/_footer.html.erb
<footer>
  <nav class="navbar fixed-bottom navbar-expand-lg navbar-dark  footer-nav bg-dark">
    <div class="mx-auto">
      <a class="navbar-brand" href="https://www.facebook.com/groups/311473876611329" target="_blank">Facebook</a>
    </div>
  </nav>
</footer>

app/views/partial/_navbar.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <%= link_to "DTM connect OKINAWA", root_path, class: "navbar__mainLogo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse bg-dark" id="navbarNav">
      <ul class="navbar-nav ml-md-auto align-items-center">
        <li>
          <%= link_to "DcOとは？", introductions_path%>
        </li>
        <li>
          <%= link_to "メンバー", members_path%>
        </li>
        <li>
          <%= link_to "作品一覧", movies_path%>
        </li>
        <li>
          <%= link_to "お問い合わせ", contacts_path%>
        </li>
      </ul>
      <ul class="navbar-nav ml-md-auto align-items-center">
        <%= link_to user_path(current_user) do %>
          <%=image_tag current_user.profile_photo.url, class: "nav-link post-profile-icon" %>
        <% end %>
        <li class="nav-item active dropdown align-items-right">
          <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.username%>
          </a>
          <div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
            <%= link_to edit_user_registration_path, class: "dropdown-item" do%>
              <i class="fas fa-edit"></i>
              <span class="mr-1">プロフィールを編集</span>
            <% end %>
            <%= link_to destroy_user_session_path, method: :delete, data: { confirm: 'サインアウトしますか？'}, class: "dropdown-item" do%>
              <i class="fas fa-door-open"></i>
              <span class="mr-1">サインアウト</span>
            <% end %>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>